on: push
jobs:
  first-job:
    runs-on: ubuntu-latest
    container: node:18.20.2
    steps:
      - run: node --version
      - run: npm --version 
      - uses: actions/checkout@v4
      - run: npm install
      - run: node index.js